### ISSUE TITLE
Stadia Controller

### ISSUE THREAD

**Issue by mgiambrone** [ihm-tswow/Links-Awakening-DX-HD#2]
Can't get it to work with a wired Stadia Controller
![image](https://github.com/ihm-tswow/Links-Awakening-DX-HD/assets/11039710/4e90a419-54d3-4f25-8d71-62ae91973835)

**Comment by tocram1** [comment]
What do you mean exactly? Controller inputs aren't detected by the game at all?

**Comment by mgiambrone** [comment]
> What do you mean exactly? Controller inputs aren't detected by the game at all?

Correct, for the game Link's Awakening HD, controller inputs are not detected at all, it's as if I don't have a controller plugged in. Doing the test in windows control panel, it shows that my controller inputs are detected by the operating system. It also works fine in other games. 

I'm using Windows 11 Pro, Stadia Controller Wired.

**Comment by mgiambrone** [comment]
used https://github.com/x360ce/x360ce to fix the issue, basically it wraps the Stadia controller into looking like an XBox 360 controller
